spring:
  application:
    name: Email Code Check API
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    user: postgres
    password: azinox21
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=notification"
    schemas: notification

server:
  servlet:
    context-path: /
  port: 8085
